name: jatimtour
description: "Touring in East Java has never been more fun!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  curved_navigation_bar: ^1.0.3
  dots_indicator: ^3.0.0
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/

  fonts:
  - family: KronaOne
    fonts: 
    - asset: assets/fonts/KronaOne/KronaOne-Regular.ttf

  - family: Inter
    fonts:
    - asset: assets/fonts/Inter/Inter-Regular.ttf
    - asset: assets/fonts/Inter/Inter-Medium.ttf
      weight: 500
    - asset: assets/fonts/Inter/Inter-Bold.ttf
      weight: 700
