name: jatimtour
description: "Touring in East Java has never been more fun!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  carousel_slider: ^4.2.1
  curved_navigation_bar: ^1.0.3
  dots_indicator: ^3.0.0
  email_validator: ^2.1.17
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_storage: ^11.7.0
  flutter:
    sdk: flutter
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  provider: ^6.1.2
  shadow_overlay: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
  - assets/images/

  fonts:
  - family: KronaOne
    fonts: 
    - asset: assets/fonts/KronaOne/KronaOne-Regular.ttf

  - family: Inter
    fonts:
    - asset: assets/fonts/Inter/Inter-Regular.ttf
    - asset: assets/fonts/Inter/Inter-Medium.ttf
      weight: 500
    - asset: assets/fonts/Inter/Inter-Bold.ttf
      weight: 700

  - family: MaisonNeue
    fonts:
      - asset: assets/fonts/MaisonNeue/MaisonNeueBold.otf
        weight: 700

  - family: CherieDEMO
    fonts:
      - asset: assets/fonts/CherieDEMO/Cherie_DEMO.ttf

  - family: CreatoDisplay
    fonts:
      - asset: assets/fonts/CreatoDisplay/CreatoDisplay-Regular.otf
      - asset: assets/fonts/CreatoDisplay/CreatoDisplay-Medium.otf
        weight: 500
      - asset: assets/fonts/CreatoDisplay/CreatoDisplay-Bold.otf
        weight: 700
      - asset: assets/fonts/CreatoDisplay/CreatoDisplay-Black.otf
        weight: 900
