name: jatimtour
description: "Touring in East Java has never been more fun!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.0.1
  columnbuilder: ^0.0.3
  curved_navigation_bar: ^1.0.6
  dev: ^1.0.0
  dots_indicator: ^3.0.0
  email_validator: ^2.1.17
  firebase_app_check: ^0.3.0+1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_modular: ^6.3.4
  flutter_quill: ^9.4.3
  image_cropper: ^7.0.5
  image_picker: ^1.1.2
  intl: ^0.19.0
  rowbuilder: ^0.0.1
  shadow_overlay: ^1.0.5
  textfield_tags:
    git:
      url: https://github.com/lionelmennig/textfield_tags.git
      ref: fixes/allow-controller-re-registration
  universal_html: ^2.2.4
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.jpg"

flutter:
  uses-material-design: true

  assets:
  - assets/images/

  fonts:
  - family: KronaOne
    fonts: 
    - asset: assets/fonts/KronaOne/KronaOne-Regular.ttf

  - family: Inter
    fonts:
    - asset: assets/fonts/Inter/Inter-Regular.ttf
    - asset: assets/fonts/Inter/Inter-Medium.ttf
      weight: 500
    - asset: assets/fonts/Inter/Inter-Bold.ttf
      weight: 700

  - family: MaisonNeue
    fonts:
      - asset: assets/fonts/MaisonNeue/MaisonNeueBold.otf
        weight: 700

  - family: CherieDEMO
    fonts:
      - asset: assets/fonts/CherieDEMO/Cherie_DEMO.ttf

  - family: CreatoDisplay
    fonts:
      - asset: assets/fonts/CreatoDisplay/CreatoDisplay-Regular.otf
      - asset: assets/fonts/CreatoDisplay/CreatoDisplay-Medium.otf
        weight: 500
      - asset: assets/fonts/CreatoDisplay/CreatoDisplay-Bold.otf
        weight: 700
      - asset: assets/fonts/CreatoDisplay/CreatoDisplay-Black.otf
        weight: 900
